# Telly role
---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: telly
    state: absent

- name: Create telly directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "/opt/telly"

- name: Create and start container
  docker_container:
    name: telly
    image: "tombowditch/telly"
    pull: yes
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/opt/telly:/opt/telly"
    - "/opt/iptv/iptv.m3u:/iptv.m3u"
    env:
      PLAYLIST: "/iptv.m3u"
      STREAMS: "5"
      LISTEN: "0.0.0.0:6077"
      BASE: "telly:6077"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    networks:
      - name: tierbox
        aliases:
          - telly
    purge_networks: yes
    restart_policy: always
    state: started
