# Telly role
---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: telly
    state: absent

- name: Create telly directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{dirs.data}}/telly"

- name: Copy configuration file
  template:
    src: "telly.config.toml.js2"
    dest: "{{dirs.data}}/telly/telly.config.toml"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0644

- name: Create and start container
  docker_container:
    name: telly
    image: "tellytv/telly:dev-ffmpeg"
    pull: yes
    ports:
      - "6077:6077/tcp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{dirs.data}}/telly/telly.config.toml:/etc/telly/telly.config.toml"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      TZ: "America/Toronto"
    networks:
      - name: tierbox
        aliases:
          - telly
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
