---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Install common packages
  apt: "name={{item}} state=present"
  with_items:
    - unrar
    - unzip
    - p7zip
    - python-pip
    - python3-pip
    - python-passlib
    - curl
    - sqlite3
    - vnstat
    - tree
    - lsof
    - man-db
    - ksmtuned
    - git
    - pwgen
    - rsync
    - logrotate
    - htop
    - iotop
    - nload
    - fail2ban
    - ufw
    - screen
    - mosh

- name: Install common pip modules
  pip: "name={{item}} state=latest executable=pip3"
  with_items:
    - docker-py
    - ansible-toolbox


- name: Create common directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{ dirs.data }}"
    - "{{ dirs.media }}"
    - "{{ dirs.data }}/scripts"
    - "{{ dirs.data }}/support_files"
