---
- name: Install required packages
  apt: "name={{item}} state=present"
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add official gpg signing key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install docker
  apt:
    name: docker-ce=18.06.1~ce~3-0~ubuntu
    state: present
    update_cache: yes
    force: yes

# - name: Prevent docker-ce from being upgraded
#   dpkg_selections:
#     name: docker-ce
#     selection: hold

- name: Start docker
  systemd: state=started name=docker enabled=yes

- name: "Wait for 30 seconds before commencing"
  wait_for:
    timeout: 30

- name: Install ctop
  get_url:
    url:  "https://github.com/bcicen/ctop/releases/download/v0.7.1/ctop-0.7.1-linux-amd64"
    dest: /usr/local/bin/ctop
    mode: 0755
    owner: root
    group: root
    force: yes
    validate_certs: no

- name: Create network
  docker_network:
    name: tierbox
    ipam_options:
      subnet: '172.33.0.0/16'
      gateway: '172.33.0.254'
      iprange: '172.33.0.0/24'

- include_role:
    name: watchtower

- include_role:
    name: glances

- include_role:
    name: backup
