---
# ZNC Bouncer role
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: znc
    state: absent

- name: Create unifi directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{dirs.data}}/znc"

- name: Create and start container
  docker_container:
    name: znc
    image: "linuxserver/znc"
    pull: yes
    published_ports:
      - "6501:6501/tcp"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "znc.{{domain}}"
      LETSENCRYPT_HOST: "znc.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{dirs.data}}/znc:/config"
    networks:
      - name: tierbox
        aliases:
          - znc
    restart_policy: always
    state: started
