---
#- name: Ensure using kernel 4.15 or newer
#  fail: msg="You must be using kernel 4.15.1-generic or newer! Use --tags \"kernel\" to upgrade first!"
#  when: ansible_kernel is version('4.15', '<')

- name: Create common groups
  group: "name={{item}} state=present"
  with_items:
    - docker
    - "{{user}}"

- name: "Create user {{user}}"
  user:
    name: "{{user}}"
    group: "{{user}}"
    groups: "{{user}},docker,sudo"
    append: yes

- name: Check rclone.service exists
  stat:
    path: "/etc/systemd/system/rclone.service"
  register: rclone_service_check

- name: Stop all docker containers
  shell: "docker stop $(docker ps -aq)"
  ignore_errors: yes
  when: rclone_service_check.stat.exists  

- name: Stop rclone service
  systemd:
    name: rclone
    state: stopped
  when: rclone_service_check.stat.exists
  
